spring.application.name=MEDICAL-ONLINE-STORE
spring.datasource.url=jdbc:mysql://localhost:3306/medical_store
spring.datasource.username=root
spring.datasource.password=root/uvpassword9969

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080


